// 📦 DIR-207 — A TELA DE PRODUTO DA GESTÃO E A RÉGUA ÚNICA DE MEDIDAS (08/10/2026)
//
// Dono: "a IA não está botando o peso correto… caso eu não importe, tem que
// ter o espaço manual" e "inseri vídeo que não está disponível quando clico
// no botão editar". A tela src/pages/AddCatalogProduct.jsx é o "Editar" da
// gestão de produtos, do card da loja e do lápis da vitrine. Estes testes leem
// o código como texto (sem comentários) e garantem que:
//   • ao abrir com sourceProduct ela carrega notes/category_id/condicao/… em vez
//     de zerar, e busca o produto FRESCO por id (o state vinha do cache velho);
//   • a IA só preenche medida VAZIA, pela régua única, e marca 'estimativa_ia';
//     digitar à mão vira 'manual'; {ok:false} da IA é falha;
//   • o pacote de gravação passa por normalizarMedidas (vazio → null, nunca 0)
//     e leva medidas_origem/medidas_em; aviso de faixa NÃO salva;
//   • a seção manual tem placeholders/steps certos, a linha do frete e o selo;
//   • o buscador manual de fotos copia para o nosso Storage antes de somar.
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { semComentarios } from './_ajuda.mjs';

const leia = (p) => fs.readFileSync(new URL(`../${p}`, import.meta.url), 'utf8');
const TELA = semComentarios(leia('src/pages/AddCatalogProduct.jsx'));

test('usa a régua única e o helper de fotos — e não tem mais cópia local da cópia de fotos', () => {
  assert.match(TELA, /import \{ normalizarMedidas, caixaDoFrete, resumoDaCaixa, faltamMedidas, textoDoCampo, ORIGENS_MEDIDA \} from '@\/lib\/medidasDoProduto'/);
  assert.match(TELA, /import \{ trazerFotosParaNosso \} from '@\/lib\/fotosParaNosso'/);
  assert.ok(!TELA.includes("from '@/lib/imagemExterna'"), 'separarFotos não é mais importado direto: a cópia mora no helper');
  assert.ok(!TELA.includes("invoke('copiarImagensParaNosso'"), 'a tela não chama a rota de cópia por conta própria');
  assert.match(TELA, /const trazerParaNosso = trazerFotosParaNosso;/);
});

test('ao abrir com sourceProduct carrega o que a tela grava (notes, category_id, condicao…) e busca o produto fresco por id', () => {
  assert.match(TELA, /description: product\.notes \|\| ''/);
  assert.match(TELA, /category: product\.category_id \|\| ''/);
  assert.match(TELA, /condicao: normalizarCondicao\(product\.condicao\) \|\| ''/);
  assert.match(TELA, /estado_conservacao: product\.estado_conservacao \|\| ''/);
  assert.match(TELA, /product_source: product\.product_source \|\| ''/);
  assert.match(TELA, /is_featured: !!product\.is_featured/);
  assert.match(TELA, /purchase_order: product\.purchase_order \|\| ''/);
  assert.match(TELA, /video_urls: Array\.isArray\(product\.video_urls\) \? product\.video_urls : \[\]/);
  // medidas carregadas pela régua (0 e null viram campo vazio)
  for (const [campo, coluna] of [['weight', 'peso'], ['length', 'comprimento'], ['height', 'altura'], ['width', 'largura']]) {
    assert.ok(TELA.includes(`${campo}: textoDoCampo(product.${coluna})`), `${campo} ← textoDoCampo(product.${coluna})`);
  }
  assert.match(TELA, /setMedidasOrigem\(product\.medidas_origem \|\| null\)/);
  // o state pode vir do cache velho (products_cache_v3): busca o fresco por id, sem travar se falhar
  assert.match(TELA, /await plataforma\.entities\.Product\.filter\(\{ id: base\.id \}\)/);
  assert.match(TELA, /if \(Array\.isArray\(achados\) && achados\[0\]\) product = achados\[0\];/);
  assert.match(TELA, /catch \{[^}]*\}/);
  assert.ok(!TELA.includes("description: '',\n        image_urls"), 'não zera mais a descrição ao abrir');
});

test('a IA só regenera a descrição sem notes gravado, e só preenche detalhes quando falta categoria ou medida', () => {
  assert.match(TELA, /if \(!String\(product\.notes \|\| ''\)\.replace\(\/<\[\^>\]\*>\/g, ''\)\.trim\(\)\) \{\s*setTimeout\(\(\) => autoGenerateDescription\(product\.description\), 800\);/);
  assert.match(TELA, /if \(!product\.category_id \|\| faltamMedidas\(product\)\) \{\s*setTimeout\(\(\) => autoFillProductDetails\(product\.description\), 1200\);/);
  // o botão "🪄 Usar IA" continua para regenerar sob clique
  assert.match(TELA, /onClick=\{handleGenerateDescription\}/);
});

test('a IA nunca sobrescreve medida preenchida: só entra em campo vazio, pela régua, e marca estimativa_ia', () => {
  assert.match(TELA, /const \{ valores: medidasIA \} = normalizarMedidas\(\{\s*peso: data\.peso_kg, altura: data\.altura_cm, comprimento: data\.comprimento_cm, largura: data\.largura_cm,/);
  assert.match(TELA, /weight: prev\.weight \|\| textoDoCampo\(medidasIA\.peso\)/);
  assert.match(TELA, /height: prev\.height \|\| textoDoCampo\(medidasIA\.altura\)/);
  assert.match(TELA, /length: prev\.length \|\| textoDoCampo\(medidasIA\.comprimento\)/);
  assert.match(TELA, /width: prev\.width \|\| textoDoCampo\(medidasIA\.largura\)/);
  assert.ok(!TELA.includes('data.peso_kg > 0 ? String(data.peso_kg)'), 'o número cru da IA não entra mais direto');
  assert.match(TELA, /if \(iaPreencheuMedida\) setMedidasOrigem\('estimativa_ia'\)/);
  // digitou à mão em qualquer um dos 4 campos → manual
  assert.match(TELA, /const CAMPOS_DE_MEDIDA_DO_FORM = \['weight', 'height', 'width', 'length'\]/);
  assert.match(TELA, /if \(CAMPOS_DE_MEDIDA_DO_FORM\.includes\(field\)\) setMedidasOrigem\('manual'\)/);
  // {ok:false} da IA é falha (antes mostrava "Categoria: undefined")
  assert.match(TELA, /if \(!response \|\| response\.ok === false\) throw new Error\('IA não retornou dados'\)/);
  // prompt e schema pedem produto (não embalagem), kg/cm, e a confiança
  assert.match(TELA, /Os números devem ser do PRODUTO \(não da embalagem\), em kg e cm, e só se você tiver certeza razoável; na dúvida, 0/);
  assert.match(TELA, /confianca: \{ type: "string", enum: \["alta", "media", "baixa"\] \}/);
});

test('o pacote de gravação passa pela régua: vazio → null (nunca 0), medidas_origem e medidas_em; aviso de faixa NÃO salva', () => {
  assert.match(TELA, /const medidas = normalizarMedidas\(medidasDoForm\(formData\)\);/);
  assert.match(TELA, /if \(medidas\.avisos\.length\) \{\s*toast\(\{ title: 'Confira as medidas antes de salvar'[^}]*variant: 'destructive' \}\);\s*setShowPublishConfirm\(false\);\s*return;/);
  assert.match(TELA, /peso: medidas\.valores\.peso,\s*comprimento: medidas\.valores\.comprimento,\s*altura: medidas\.valores\.altura,\s*largura: medidas\.valores\.largura,/);
  assert.ok(!TELA.includes('parseFloat(formData.weight) || 0'), 'peso nunca mais vira 0 por padrão');
  assert.match(TELA, /medidas_origem: temMedida \? medidasOrigem : null/);
  assert.match(TELA, /\.\.\.\(medidaMudou \? \{ medidas_em: new Date\(\)\.toISOString\(\) \} : \{\}\)/);
  assert.match(TELA, /const medidaMudou = temMedida && Object\.keys\(medidas\.valores\)\.some\(\(c\) => medidas\.valores\[c\] !== antes\[c\]\)/);
  // os campos que faltavam continuam indo (e agora saem carregados, não zerados)
  for (const k of ['category_id: formData.category || null', 'condicao: formData.condicao || null', 'is_featured: formData.is_featured', 'purchase_order: formData.purchase_order']) {
    assert.ok(TELA.includes(k), `payload leva ${k}`);
  }
});

test('seção manual: peso 0,000 / step 0.001, cm step 0.1 / placeholder 0, avisos ao vivo, linha do frete e selo de origem', () => {
  assert.match(TELA, /step="0\.001"\s*value=\{formData\.weight\}[\s\S]*?placeholder="0,000"/);
  for (const campo of ['height', 'length', 'width']) {
    assert.match(TELA, new RegExp(`step="0\\.1"\\s*value=\\{formData\\.${campo}\\}[\\s\\S]*?placeholder="0"`), `${campo} em cm com step 0.1 e placeholder 0`);
  }
  assert.ok(!TELA.includes('placeholder="0cm"'), 'o placeholder "0cm" no peso em kg sumiu');
  assert.match(TELA, /const \{ avisos: avisosMedidas \} = normalizarMedidas\(medidasDoForm\(formData\)\);/);
  assert.match(TELA, /const caixaDoFreteAgora = caixaDoFrete\(medidasDoForm\(formData\)\);/);
  assert.match(TELA, /O frete vai cotar com: <strong>\{resumoDaCaixa\(caixaDoFreteAgora\)\}<\/strong>/);
  assert.match(TELA, /caixaDoFreteAgora\.padrao && \([\s\S]*?text-red-600">⚠️ caixa padrão<\/span>/);
  assert.match(TELA, /\{medidasOrigem && ORIGENS_MEDIDA\[medidasOrigem\] && \(/);
  for (const t of ['medidas-do-produto', 'avisos-de-medida', 'frete-caixa', 'origem-da-medida']) {
    assert.ok(TELA.includes(`data-teste="${t}"`), `data-teste ${t}`);
  }
});

test('o buscador manual de fotos copia para o nosso Storage antes de somar e avisa quantas falharam', () => {
  assert.match(TELA, /onSelect=\{async \(urls\) => \{[\s\S]*?const \{ fotos, falharam \} = await trazerFotosParaNosso\(urls, formData\.title\);[\s\S]*?image_urls: \[\.\.\.prev\.image_urls, \.\.\.fotos\.filter\(u => !prev\.image_urls\.includes\(u\)\)\]/);
  assert.match(TELA, /não puderam ser copiadas e ficaram de fora/);
  assert.ok(!TELA.includes('...urls.filter(u => !prev.image_urls.includes(u))'), 'as urls cruas do buscador não entram mais direto');
});
